node_js: 
  - "0.10"
language: node_js
env: 
  global: 
  - AWS_DEFAULT_REGION=ap-southeast-2
  - secure: YIqfbHGH8JVxU8kJwtafTwS7CRUAnZANYLQt7Iry8F27MlRzLLtLGaST1biR3ZV8wtKWXzUNmh+wbWR+cDdTeusQ1KahNTGgBRAJlclynzEHpq8z3l0S5f8LIDkoaPxXuu94d1OBAlO7kY3yBwtV6KhJPFQX7cvzkmy0nT4fDyE=
  - secure: nvj4vUeM7jM09VrKvDErJNyb/HPBY+FjYHre0KcJFAN6nBbjA05lx6McUo7BfJgkU7fmVpg68OrGL8uFZ+vNVLgKgIBDwGris27oDs0wrPpRKUWpvd6POtrcJAXHXWesNhYRT8brXjLz4ar1rcjhC2ZiRJvP7cfEASsjMXMsz9o=
after_success: 
  - sudo pip install awscli
  - zip -r nationalmap2.zip package.json main.js public
  - aws s3 cp nationalmap2.zip s3://nationalmap-beanstalk/nationalmap2-`git rev-parse --short HEAD`.zip
  - aws elasticbeanstalk create-application-version --application-name "nationalmap2" --version-label `git rev-parse --short HEAD` --source-bundle S3Bucket="nationalmap-beanstalk",S3Key="nationalmap2-`git rev-parse --short HEAD`.zip"
  - aws elasticbeanstalk update-environment --environment-name "nationalmap2-env" --version-label `git rev-parse --short HEAD`
